DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS posts;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	user_name TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	password_digest TEXT NOT NULL UNIQUE,
 );

CREATE TABLE recipes (
	id SERIAL PRIMARY KEY,
	recipe_name TEXT NOT NULL,
	main_ingredient TEXT NOT NULL,

	body VARCHAR(500) NOT NULL,
	image TEXT,
);

